-- 工资表主表
CREATE TABLE `Bil_Salary_Slip` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '唯一值（ID）',
  `createuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  `description` text COLLATE utf8mb4_general_ci COMMENT '摘要',
  `lingma_sys_is_delete` int DEFAULT 0 COMMENT '是否删除',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `status` int DEFAULT 1 COMMENT '状态',
  `slip_no` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工资表编号',
  `salary_month` varchar(7) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工资月份 YYYY-MM',
  `depart_name` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '部门名称',
  `project_name` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '项目名称',
  `employee_count` int DEFAULT 0 COMMENT '人数',
  `total_should_pay` decimal(18,2) DEFAULT 0.00 COMMENT '应发工资合计',
  `total_deduct_pay` decimal(18,2) DEFAULT 0.00 COMMENT '扣减合计',
  `total_tax` decimal(18,2) DEFAULT 0.00 COMMENT '个税合计',
  `total_actual_pay` decimal(18,2) DEFAULT 0.00 COMMENT '实发工资合计',
  `paid_salary` decimal(18,2) DEFAULT 0.00 COMMENT '已发工资',
  `write_off_amount` decimal(18,2) DEFAULT 0.00 COMMENT '核销金额',
  `remaining_should_pay` decimal(18,2) DEFAULT 0.00 COMMENT '应发余额',
  `account_set_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '帐套ID',
  PRIMARY KEY (`rowid`),
  KEY `idx_salary_slip_month` (`salary_month`),
  KEY `idx_salary_slip_set` (`account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工资表主表';

-- 工资表明细值表（一行员工 * 多个工资项）
CREATE TABLE `Bil_Salary_Slip_Item` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '唯一值（ID）',
  `createuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  `description` text COLLATE utf8mb4_general_ci COMMENT '摘要',
  `lingma_sys_is_delete` int DEFAULT 0 COMMENT '是否删除',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `status` int DEFAULT 1 COMMENT '状态',
  `slip_id` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工资表ID',
  `line_no` int DEFAULT 1 COMMENT '行号',
  `employee_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '员工姓名',
  `detail_depart_name` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '明细部门',
  `detail_project_name` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '明细项目',
  `expense_category` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '费用类别',
  `item_code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工资项编码',
  `item_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工资项名称',
  `item_direction` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '项目方向',
  `item_category` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '项目分类',
  `item_value` decimal(18,2) DEFAULT 0.00 COMMENT '工资项金额',
  `should_pay` decimal(18,2) DEFAULT 0.00 COMMENT '应发合计',
  `deduct_total` decimal(18,2) DEFAULT 0.00 COMMENT '扣减合计',
  `tax_value` decimal(18,2) DEFAULT 0.00 COMMENT '个税',
  `real_pay` decimal(18,2) DEFAULT 0.00 COMMENT '实发工资',
  `company_social` decimal(18,2) DEFAULT 0.00 COMMENT '公司社保',
  `company_fund` decimal(18,2) DEFAULT 0.00 COMMENT '公司公积金',
  `account_set_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '帐套ID',
  PRIMARY KEY (`rowid`),
  KEY `idx_salary_slip_item_slip` (`slip_id`),
  KEY `idx_salary_slip_item_emp` (`employee_name`),
  KEY `idx_salary_slip_item_set` (`account_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工资表明细值表';
