CREATE TABLE `Bil_Dimension_Rule` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键',
  `rule_code` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则编码',
  `rule_name` varchar(200) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则名称',
  `event_code` varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT '事件编码',
  `biz_category` varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务分类',
  `account_set_id` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '账套ID',
  `priority` int NOT NULL DEFAULT 100 COMMENT '优先级',
  `voucher_required` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否需要凭证',
  `auto_voucher_write` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否自动写凭证',
  `status` bit(1) NOT NULL DEFAULT b'1' COMMENT '启用状态',
  `stop_after_match` bit(1) NOT NULL DEFAULT b'1' COMMENT '命中后停止',
  `description` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '描述',
  `lingma_sys_ent` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '租户/企业编码',
  `lingma_sys_is_delete` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否软删除',
  `createuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_dimension_rule_code` (`rule_code`),
  KEY `idx_dimension_rule_event_code` (`event_code`),
  KEY `idx_dimension_rule_biz_category` (`biz_category`),
  KEY `idx_dimension_rule_account_set_id` (`account_set_id`),
  KEY `idx_dimension_rule_is_delete` (`lingma_sys_is_delete`),
  KEY `idx_dimension_rule_status_priority` (`status`,`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='维度规则主表';

CREATE TABLE `Bil_Dimension_Rule_Condition` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键',
  `rule_id` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则ID',
  `sort_no` int NOT NULL DEFAULT 1 COMMENT '排序号',
  `field_code` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '字段编码',
  `operator` varchar(30) COLLATE utf8mb4_general_ci NOT NULL COMMENT '运算符',
  `value_source` varchar(20) COLLATE utf8mb4_general_ci NOT NULL COMMENT '取值来源 CONST/FIELD',
  `compare_value` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '比较值',
  `compare_field` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '比较字段',
  `description` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '描述',
  `lingma_sys_ent` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '租户/企业编码',
  `lingma_sys_is_delete` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否软删除',
  `createuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  PRIMARY KEY (`rowid`),
  KEY `idx_dimension_rule_condition_rule_id` (`rule_id`),
  KEY `idx_dimension_rule_condition_sort_no` (`sort_no`),
  KEY `idx_dimension_rule_condition_is_delete` (`lingma_sys_is_delete`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='维度规则条件表';

CREATE TABLE `Bil_Dimension_Rule_Result` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键',
  `rule_id` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则ID',
  `sort_no` int NOT NULL DEFAULT 1 COMMENT '排序号',
  `dim_category` varchar(30) COLLATE utf8mb4_general_ci NOT NULL COMMENT '维度分类',
  `dim_code` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '维度编码',
  `value_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL COMMENT '取值方式',
  `value_expr` varchar(500) COLLATE utf8mb4_general_ci NOT NULL COMMENT '取值表达式',
  `amount_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'NONE' COMMENT '金额方式',
  `amount_expr` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '金额表达式',
  `direction_type` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '方向方式',
  `direction_expr` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '方向表达式',
  `currency_type` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '币种方式',
  `currency_expr` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '币种表达式',
  `period_type` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期间方式',
  `period_expr` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期间表达式',
  `required_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必填',
  `description` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '描述',
  `lingma_sys_ent` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '租户/企业编码',
  `lingma_sys_is_delete` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否软删除',
  `createuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  PRIMARY KEY (`rowid`),
  KEY `idx_dimension_rule_result_rule_id` (`rule_id`),
  KEY `idx_dimension_rule_result_sort_no` (`sort_no`),
  KEY `idx_dimension_rule_result_dim_code` (`dim_code`),
  KEY `idx_dimension_rule_result_is_delete` (`lingma_sys_is_delete`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='维度规则结果表';

INSERT INTO `Bil_Dimension_Rule` (`rowid`,`rule_code`,`rule_name`,`event_code`,`biz_category`,`account_set_id`,`priority`,`voucher_required`,`auto_voucher_write`,`status`,`stop_after_match`,`description`,`lingma_sys_ent`,`lingma_sys_is_delete`,`createuser`,`createtime`,`updateuser`,`updatetime`,`wfid`,`flowstate`,`ReportID`) VALUES
('RULE_TEST_SALE_SHIPMENT','DIM_RULE_SALE_SHIPMENT_TEST','销售出库审批测试规则','SALE_SHIPMENT','销售','AS1001',999,b'1',b'1',b'1',b'1','销售出库审批主规则：当前先以这条规则承载正式销售发货分录逻辑。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RULE001','DIM_RULE_SALE_SHIPMENT_DIST','销售发货审批规则','SALE_SHIPMENT','销售','AS1001',100,b'1',b'1',b'1',b'1','保留的正式销售发货规则，当前优先级低于测试主规则。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RULE002','DIM_RULE_SALE_RETURN_DIST','销售退货-经销渠道规则','SALE_RETURN','销售','AS1001',100,b'1',b'0',b'1',b'1','适用于苏居经销商渠道的退货逆向维度。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RULE003','DIM_RULE_COLLECTION_GOODS','收款确认-货款规则','COLLECTION_SUBMIT_CONFIRM','收款','AS1001',100,b'1',b'1',b'1',b'1','适用于苏居货款类收款确认。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL);

INSERT INTO `Bil_Dimension_Rule_Condition` (`rowid`,`rule_id`,`sort_no`,`field_code`,`operator`,`value_source`,`compare_value`,`compare_field`,`description`,`lingma_sys_ent`,`lingma_sys_is_delete`,`createuser`,`createtime`,`updateuser`,`updatetime`,`wfid`,`flowstate`,`ReportID`) VALUES
('COND_TEST_001','RULE_TEST_SALE_SHIPMENT',1,'status','equal','CONST','10',NULL,'销售出库单在待审批状态时允许触发测试预览。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('COND_TEST_002','RULE_TEST_SALE_SHIPMENT',2,'customer_id','notnull','CONST','',NULL,'客户不能为空。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('COND001','RULE001',1,'customer_id','notnull','CONST','',NULL,'客户不能为空。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('COND002','RULE001',2,'status','equal','CONST','10',NULL,'销售出库单在审批前预览阶段命中正式规则。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('COND003','RULE002',1,'customer_type','equal','CONST','经销商',NULL,'经销商渠道退货。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('COND004','RULE003',1,'income_type','equal','CONST','货款',NULL,'仅处理货款类收款。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL);

INSERT INTO `Bil_Dimension_Rule_Result` (`rowid`,`rule_id`,`sort_no`,`dim_category`,`dim_code`,`value_type`,`value_expr`,`amount_type`,`amount_expr`,`direction_type`,`direction_expr`,`currency_type`,`currency_expr`,`period_type`,`period_expr`,`required_flag`,`description`,`lingma_sys_ent`,`lingma_sys_is_delete`,`createuser`,`createtime`,`updateuser`,`updatetime`,`wfid`,`flowstate`,`ReportID`) VALUES
('RES_TEST_001','RULE_TEST_SALE_SHIPMENT',1,'FINANCIAL','SUBJECT','CONST','1122','FIELD','total_price','CONST','DEBIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','借：应收账款。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES_TEST_002','RULE_TEST_SALE_SHIPMENT',2,'FINANCIAL','SUBJECT','CONST','6001','FIELD','total_price','CONST','CREDIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','贷：主营业务收入。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES_TEST_003','RULE_TEST_SALE_SHIPMENT',3,'FINANCIAL','SUBJECT','CONST','6401','FIELD','total_price','CONST','DEBIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','借：主营业务成本。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES_TEST_004','RULE_TEST_SALE_SHIPMENT',4,'FINANCIAL','SUBJECT','CONST','1405','FIELD','total_price','CONST','CREDIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','贷：库存商品。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES_TEST_005','RULE_TEST_SALE_SHIPMENT',5,'BIZ','CUSTOMER','FIELD','customer_id','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'1','客户维度。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES_TEST_006','RULE_TEST_SALE_SHIPMENT',6,'BIZ','DEPT','FIELD','sale_dept_id','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'1','销售归属部门。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES_TEST_007','RULE_TEST_SALE_SHIPMENT',7,'ANALYSIS','ORDER_NO','FIELD','order_no','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'0','订单号。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES001','RULE001',1,'FINANCIAL','SUBJECT','CONST','1122','FIELD','total_price','CONST','DEBIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','借：应收账款。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES002','RULE001',2,'FINANCIAL','SUBJECT','CONST','6001','FIELD','total_price','CONST','CREDIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','贷：主营业务收入。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES003','RULE001',3,'FINANCIAL','SUBJECT','CONST','6401','FIELD','total_price','CONST','DEBIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','借：主营业务成本。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES004','RULE001',4,'FINANCIAL','SUBJECT','CONST','1405','FIELD','total_price','CONST','CREDIT','CONST','CNY','FUNC','formatPeriod(out_time)',b'1','贷：库存商品。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES005','RULE001',5,'BIZ','CUSTOMER','FIELD','customer_id','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'1','客户维度。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES006','RULE001',6,'BIZ','DEPT','FIELD','sale_dept_id','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'1','销售归属部门。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES016','RULE001',7,'ANALYSIS','CHANNEL','FIELD','channel','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'0','销售渠道。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES017','RULE001',8,'ANALYSIS','CUSTOMER_LEVEL','DICT','CUSTOMER_LEVEL_MAP:customer_level','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'0','客户等级映射。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES007','RULE002',1,'FINANCIAL','SUBJECT','CONST','1405','FIELD','total_price','CONST','OUTFLOW','CONST','CNY','FUNC','formatPeriod(return_time)',b'1','退货冲减库存。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES008','RULE002',2,'FINANCIAL','SUBJECT','CONST','6401','FIELD','total_price','CONST','INFLOW','CONST','CNY','FUNC','formatPeriod(return_time)',b'1','退货冲减收入。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES009','RULE002',3,'BIZ','CUSTOMER','FIELD','customer_id','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'1','客户维度。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES010','RULE002',4,'BIZ','DEPT','FIELD','sale_dept_id','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'1','销售归属部门。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES011','RULE003',1,'FINANCIAL','SUBJECT','FIELD','debit_subject_no','FIELD','collection_amount','CONST','INFLOW','CONST','CNY','FUNC','formatPeriod(collection_date)',b'1','借方科目。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES012','RULE003',2,'FINANCIAL','SUBJECT','FIELD','credit_subject_no','FIELD','collection_amount','CONST','OUTFLOW','CONST','CNY','FUNC','formatPeriod(collection_date)',b'1','贷方科目。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES013','RULE003',3,'BIZ','CUSTOMER','FIELD','customer_id','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'1','客户维度。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES014','RULE003',4,'BIZ','DEPT','FIELD','depart_name','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'0','收款归属部门。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('RES015','RULE003',5,'ANALYSIS','INCOME_TYPE','FIELD','income_type','NONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,b'0','收款类型。',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL);


CREATE TABLE `Bil_Dimension_Biz_Category` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键',
  `biz_category_code` varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务分类编码',
  `biz_category_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务分类名称',
  `sort_no` int NOT NULL DEFAULT 1 COMMENT '排序号',
  `status` bit(1) NOT NULL DEFAULT b'1' COMMENT '状态',
  `description` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '描述',
  `lingma_sys_ent` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '租户/企业编码',
  `lingma_sys_is_delete` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否软删除',
  `createuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_dimension_biz_category_code` (`biz_category_code`),
  KEY `idx_dimension_biz_category_status` (`status`,`sort_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='维度业务分类字典表';

INSERT INTO `Bil_Dimension_Biz_Category` (`rowid`,`biz_category_code`,`biz_category_name`,`sort_no`,`status`,`description`,`lingma_sys_ent`,`lingma_sys_is_delete`,`createuser`,`createtime`,`updateuser`,`updatetime`,`wfid`,`flowstate`,`ReportID`) VALUES
('BIZ_CATEGORY_SALE','SALE','销售',1,b'1','销售业务',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('BIZ_CATEGORY_COLLECTION','COLLECTION','收款',2,b'1','收款业务',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('BIZ_CATEGORY_PURCHASE','PURCHASE','采购',3,b'1','采购业务',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL),
('BIZ_CATEGORY_INVENTORY','INVENTORY','库存',4,b'1','库存业务',NULL,b'0','system',NOW(),'system',NOW(),NULL,0,NULL);
