/* ============================================================
   财务辅助核算专用档案表
   说明：
   1. 供应商、客户、部门、项目、员工均为财务专用档案；
   2. 不与 ERP / CRM / HR / 项目 / 部门等业务表建立外键；
   3. source_system / source_table / source_row_id / source_code 仅做来源追溯；
   4. 不建立统一索引表；
   5. 沿用现有系统字段风格：
      row_id / account_set_id / lingma_sys_ent / lingma_sys_is_delete
      createuser / createtime / updateuser / updatetime
   ============================================================ */

CREATE TABLE IF NOT EXISTS `Bil_Fin_Aux_Supplier` (
  `row_id` varchar(32) NOT NULL COMMENT '唯一值ID',
  `supplier_code` varchar(50) NOT NULL COMMENT '财务供应商编码',
  `supplier_name` varchar(200) NOT NULL COMMENT '财务供应商名称',
  `supplier_short_name` varchar(100) DEFAULT NULL COMMENT '供应商简称',
  `tax_no` varchar(50) DEFAULT NULL COMMENT '纳税人识别号',
  `contact_name` varchar(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(30) DEFAULT NULL COMMENT '联系电话',
  `contact_mobile` varchar(30) DEFAULT NULL COMMENT '联系人手机',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `bank_name` varchar(100) DEFAULT NULL COMMENT '开户行',
  `bank_account` varchar(100) DEFAULT NULL COMMENT '银行账号',
  `bank_address` varchar(100) DEFAULT NULL COMMENT '开户地址',
  `source_system` varchar(64) DEFAULT NULL COMMENT '来源系统，如ERP/CRM/IMPORT',
  `source_table` varchar(64) DEFAULT NULL COMMENT '来源表名，仅记录，不设外键',
  `source_row_id` varchar(64) DEFAULT NULL COMMENT '来源业务ID，仅记录，不设外键',
  `source_code` varchar(64) DEFAULT NULL COMMENT '来源业务编码，仅记录，不设外键',
  `enabled` tinyint DEFAULT '1' COMMENT '启用状态：1启用 0停用',
  `sort_no` int DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `lingma_sys_ent` varchar(50) DEFAULT NULL COMMENT '企业标识',
  `lingma_sys_is_delete` int DEFAULT '0' COMMENT '是否删除：0正常 1删除',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表id',
  `description` text COMMENT '摘要',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `uk_fin_aux_supplier_code` (`account_set_id`, `lingma_sys_ent`, `supplier_code`, `lingma_sys_is_delete`),
  KEY `idx_fin_aux_supplier_name` (`account_set_id`, `lingma_sys_ent`, `supplier_name`),
  KEY `idx_fin_aux_supplier_source` (`source_system`, `source_table`, `source_row_id`),
  KEY `idx_fin_aux_supplier_ent` (`lingma_sys_ent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='财务辅助核算-供应商档案';

CREATE TABLE IF NOT EXISTS `Bil_Fin_Aux_Customer` (
  `row_id` varchar(32) NOT NULL COMMENT '唯一值ID',
  `customer_code` varchar(50) NOT NULL COMMENT '财务客户编码',
  `customer_name` varchar(200) NOT NULL COMMENT '财务客户名称',
  `customer_short_name` varchar(100) DEFAULT NULL COMMENT '客户简称',
  `tax_no` varchar(50) DEFAULT NULL COMMENT '纳税人识别号',
  `contact_name` varchar(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(30) DEFAULT NULL COMMENT '联系电话',
  `contact_mobile` varchar(30) DEFAULT NULL COMMENT '联系人手机',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `bank_name` varchar(100) DEFAULT NULL COMMENT '开户行',
  `bank_account` varchar(100) DEFAULT NULL COMMENT '银行账号',
  `source_system` varchar(64) DEFAULT NULL COMMENT '来源系统，如CRM/ERP/IMPORT',
  `source_table` varchar(64) DEFAULT NULL COMMENT '来源表名，仅记录，不设外键',
  `source_row_id` varchar(64) DEFAULT NULL COMMENT '来源业务ID，仅记录，不设外键',
  `source_code` varchar(64) DEFAULT NULL COMMENT '来源业务编码，仅记录，不设外键',
  `enabled` tinyint DEFAULT '1' COMMENT '启用状态：1启用 0停用',
  `sort_no` int DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `lingma_sys_ent` varchar(50) DEFAULT NULL COMMENT '企业标识',
  `lingma_sys_is_delete` int DEFAULT '0' COMMENT '是否删除：0正常 1删除',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表id',
  `description` text COMMENT '摘要',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `uk_fin_aux_customer_code` (`account_set_id`, `lingma_sys_ent`, `customer_code`, `lingma_sys_is_delete`),
  KEY `idx_fin_aux_customer_name` (`account_set_id`, `lingma_sys_ent`, `customer_name`),
  KEY `idx_fin_aux_customer_source` (`source_system`, `source_table`, `source_row_id`),
  KEY `idx_fin_aux_customer_ent` (`lingma_sys_ent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='财务辅助核算-客户档案';

CREATE TABLE IF NOT EXISTS `Bil_Fin_Aux_Department` (
  `row_id` varchar(32) NOT NULL COMMENT '唯一值ID',
  `department_code` varchar(50) NOT NULL COMMENT '财务部门编码',
  `department_name` varchar(200) NOT NULL COMMENT '财务部门名称',
  `department_short_name` varchar(100) DEFAULT NULL COMMENT '部门简称',
  `parent_department_code` varchar(50) DEFAULT NULL COMMENT '上级财务部门编码快照，不设外键',
  `parent_department_name` varchar(200) DEFAULT NULL COMMENT '上级财务部门名称快照',
  `source_system` varchar(64) DEFAULT NULL COMMENT '来源系统，如OA/HR/IMPORT',
  `source_table` varchar(64) DEFAULT NULL COMMENT '来源表名，仅记录，不设外键',
  `source_row_id` varchar(64) DEFAULT NULL COMMENT '来源业务ID，仅记录，不设外键',
  `source_code` varchar(64) DEFAULT NULL COMMENT '来源业务编码，仅记录，不设外键',
  `enabled` tinyint DEFAULT '1' COMMENT '启用状态：1启用 0停用',
  `sort_no` int DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `lingma_sys_ent` varchar(50) DEFAULT NULL COMMENT '企业标识',
  `lingma_sys_is_delete` int DEFAULT '0' COMMENT '是否删除：0正常 1删除',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表id',
  `description` text COMMENT '摘要',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `uk_fin_aux_dept_code` (`account_set_id`, `lingma_sys_ent`, `department_code`, `lingma_sys_is_delete`),
  KEY `idx_fin_aux_dept_name` (`account_set_id`, `lingma_sys_ent`, `department_name`),
  KEY `idx_fin_aux_dept_parent` (`account_set_id`, `lingma_sys_ent`, `parent_department_code`),
  KEY `idx_fin_aux_dept_source` (`source_system`, `source_table`, `source_row_id`),
  KEY `idx_fin_aux_dept_ent` (`lingma_sys_ent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='财务辅助核算-部门档案';

CREATE TABLE IF NOT EXISTS `Bil_Fin_Aux_Project` (
  `row_id` varchar(32) NOT NULL COMMENT '唯一值ID',
  `project_code` varchar(50) NOT NULL COMMENT '财务项目编码',
  `project_name` varchar(200) NOT NULL COMMENT '财务项目名称',
  `project_type` varchar(50) DEFAULT NULL COMMENT '项目类型',
  `project_group` varchar(50) DEFAULT NULL COMMENT '项目组',
  `customer_code` varchar(50) DEFAULT NULL COMMENT '客户编码快照，不设外键',
  `customer_name` varchar(200) DEFAULT NULL COMMENT '客户名称快照',
  `department_code` varchar(50) DEFAULT NULL COMMENT '所属部门编码快照，不设外键',
  `department_name` varchar(200) DEFAULT NULL COMMENT '所属部门名称快照',
  `manager_code` varchar(50) DEFAULT NULL COMMENT '项目负责人编码快照，不设外键',
  `manager_name` varchar(100) DEFAULT NULL COMMENT '项目负责人名称快照',
  `start_date` datetime DEFAULT NULL COMMENT '项目开始日期',
  `end_date` datetime DEFAULT NULL COMMENT '项目结束日期',
  `project_amount` decimal(18,2) DEFAULT NULL COMMENT '项目金额',
  `source_system` varchar(64) DEFAULT NULL COMMENT '来源系统，如PM/CRM/IMPORT',
  `source_table` varchar(64) DEFAULT NULL COMMENT '来源表名，仅记录，不设外键',
  `source_row_id` varchar(64) DEFAULT NULL COMMENT '来源业务ID，仅记录，不设外键',
  `source_code` varchar(64) DEFAULT NULL COMMENT '来源业务编码，仅记录，不设外键',
  `enabled` tinyint DEFAULT '1' COMMENT '启用状态：1启用 0停用',
  `sort_no` int DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `lingma_sys_ent` varchar(50) DEFAULT NULL COMMENT '企业标识',
  `lingma_sys_is_delete` int DEFAULT '0' COMMENT '是否删除：0正常 1删除',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表id',
  `description` text COMMENT '摘要',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `uk_fin_aux_project_code` (`account_set_id`, `lingma_sys_ent`, `project_code`, `lingma_sys_is_delete`),
  KEY `idx_fin_aux_project_name` (`account_set_id`, `lingma_sys_ent`, `project_name`),
  KEY `idx_fin_aux_project_type` (`account_set_id`, `lingma_sys_ent`, `project_type`),
  KEY `idx_fin_aux_project_source` (`source_system`, `source_table`, `source_row_id`),
  KEY `idx_fin_aux_project_ent` (`lingma_sys_ent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='财务辅助核算-项目档案';

CREATE TABLE IF NOT EXISTS `Bil_Fin_Aux_Employee` (
  `row_id` varchar(32) NOT NULL COMMENT '唯一值ID',
  `employee_code` varchar(50) NOT NULL COMMENT '财务员工编码',
  `employee_name` varchar(100) NOT NULL COMMENT '财务员工姓名',
  `department_code` varchar(50) DEFAULT NULL COMMENT '所属财务部门编码快照，不设外键',
  `department_name` varchar(200) DEFAULT NULL COMMENT '所属财务部门名称快照',
  `position_name` varchar(100) DEFAULT NULL COMMENT '岗位名称',
  `mobile` varchar(30) DEFAULT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `source_system` varchar(64) DEFAULT NULL COMMENT '来源系统，如HR/OA/IMPORT',
  `source_table` varchar(64) DEFAULT NULL COMMENT '来源表名，仅记录，不设外键',
  `source_row_id` varchar(64) DEFAULT NULL COMMENT '来源业务ID，仅记录，不设外键',
  `source_code` varchar(64) DEFAULT NULL COMMENT '来源业务编码，仅记录，不设外键',
  `enabled` tinyint DEFAULT '1' COMMENT '启用状态：1启用 0停用',
  `sort_no` int DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `lingma_sys_ent` varchar(50) DEFAULT NULL COMMENT '企业标识',
  `lingma_sys_is_delete` int DEFAULT '0' COMMENT '是否删除：0正常 1删除',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表id',
  `description` text COMMENT '摘要',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `uk_fin_aux_employee_code` (`account_set_id`, `lingma_sys_ent`, `employee_code`, `lingma_sys_is_delete`),
  KEY `idx_fin_aux_employee_name` (`account_set_id`, `lingma_sys_ent`, `employee_name`),
  KEY `idx_fin_aux_employee_dept` (`account_set_id`, `lingma_sys_ent`, `department_code`),
  KEY `idx_fin_aux_employee_source` (`source_system`, `source_table`, `source_row_id`),
  KEY `idx_fin_aux_employee_ent` (`lingma_sys_ent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='财务辅助核算-员工档案';
