CREATE TABLE IF NOT EXISTS `Bil_Salary_Item_Formula` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '唯一值（ID）',
  `createuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  `description` text COLLATE utf8mb4_general_ci COMMENT '摘要',
  `lingma_sys_is_delete` int DEFAULT 0 COMMENT '是否删除',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `status` int DEFAULT 1 COMMENT '状态',
  `formula_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '公式名称',
  `target_item_code` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '目标项目编码',
  `formula_expr` text COLLATE utf8mb4_general_ci NOT NULL COMMENT '公式表达式',
  `depends_on` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '依赖项目编码，逗号分隔',
  `calc_order` int DEFAULT 0 COMMENT '计算顺序',
  `round_mode` varchar(20) COLLATE utf8mb4_general_ci DEFAULT 'ROUND' COMMENT '舍入方式',
  `is_enabled` tinyint(1) DEFAULT 1 COMMENT '是否启用',
  `account_set_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '帐套ID',
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_salary_item_formula_target_set` (`target_item_code`,`account_set_id`),
  KEY `idx_salary_item_formula_set` (`account_set_id`),
  KEY `idx_salary_item_formula_order` (`calc_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工资项目公式表';
