CREATE TABLE IF NOT EXISTS `Bil_Salary_Rule_Assignment` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '唯一值（ID）',
  `createuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  `description` text COLLATE utf8mb4_general_ci COMMENT '说明',
  `lingma_sys_is_delete` int DEFAULT 0 COMMENT '是否删除',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `status` int DEFAULT 1 COMMENT '状态',
  `rule_type` varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则类型：SOCIAL/HOUSING_FUND/TAX',
  `rule_code` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则编码，对应 Bil_Salary_Rule.rule_code',
  `apply_scope` varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'GLOBAL' COMMENT '适用范围：EMPLOYEE/RANK/DEPT/GLOBAL',
  `employee_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '员工ID',
  `rank_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '职级ID',
  `rank_code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '职级编码',
  `dept_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '部门ID',
  `effective_start_period` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生效开始期间',
  `effective_end_period` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生效结束期间',
  `priority` int DEFAULT 100 COMMENT '优先级，数值越小优先级越高',
  `is_enabled` tinyint(1) DEFAULT 1 COMMENT '是否启用',
  `account_set_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '帐套ID',
  PRIMARY KEY (`rowid`),
  KEY `idx_salary_rule_assign_rule` (`rule_type`,`rule_code`,`account_set_id`),
  KEY `idx_salary_rule_assign_scope` (`apply_scope`,`employee_id`,`rank_id`,`dept_id`,`account_set_id`),
  KEY `idx_salary_rule_assign_period` (`effective_start_period`,`effective_end_period`),
  KEY `idx_salary_rule_assign_enabled` (`is_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='薪酬规则适用关系表';
