CREATE TABLE IF NOT EXISTS `Bil_Salary_Item_Meta` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '唯一值（ID）',
  `createuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  `description` text COLLATE utf8mb4_general_ci COMMENT '摘要',
  `lingma_sys_is_delete` int DEFAULT 0 COMMENT '是否删除',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `status` int DEFAULT 1 COMMENT '状态',
  `item_code` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '项目编码',
  `item_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '名称',
  `default_value` decimal(18,2) DEFAULT NULL COMMENT '默认值',
  `default_source` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '默认值来源',
  `is_tax_item` tinyint(1) DEFAULT 0 COMMENT '计税项',
  `is_formula_item` tinyint(1) DEFAULT 0 COMMENT '公式项',
  `is_bonus_item` tinyint(1) DEFAULT 0 COMMENT '奖金项',
  `is_custom_item` tinyint(1) DEFAULT 0 COMMENT '自定义项',
  `salary_slip_display` varchar(100) COLLATE utf8mb4_general_ci DEFAULT 'ALL' COMMENT '工资条显示规则',
  `setting_permission` varchar(50) COLLATE utf8mb4_general_ci DEFAULT 'FIN' COMMENT '设置权限',
  `item_direction` varchar(20) COLLATE utf8mb4_general_ci DEFAULT 'income' COMMENT '项目方向 income/deduct/result/middle',
  `is_enabled` tinyint(1) DEFAULT 1 COMMENT '是否启用',
  `sort_no` int DEFAULT 0 COMMENT '显示排序',
  `account_set_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '帐套ID',
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_salary_item_meta_code_set` (`item_code`,`account_set_id`),
  KEY `idx_salary_item_meta_set` (`account_set_id`),
  KEY `idx_salary_item_meta_flags` (`is_formula_item`,`is_tax_item`,`is_bonus_item`,`is_custom_item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工资项目元数据表';
