CREATE TABLE IF NOT EXISTS `Bil_Salary_Rule` (
  `rowid` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '唯一值（ID）',
  `createuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例id',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报表id',
  `description` text COLLATE utf8mb4_general_ci COMMENT '规则说明',
  `lingma_sys_is_delete` int DEFAULT 0 COMMENT '是否删除',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `status` int DEFAULT 1 COMMENT '状态',
  `rule_type` varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则类型：TAX/SOCIAL/HOUSING_FUND',
  `rule_code` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则编码',
  `rule_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则名称',
  `base_item_codes` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '基数来源项目编码，逗号分隔',
  `rule_json` longtext COLLATE utf8mb4_general_ci COMMENT '规则明细JSON',
  `effective_start_period` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生效开始期间',
  `effective_end_period` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生效结束期间',
  `is_enabled` tinyint(1) DEFAULT 1 COMMENT '是否启用',
  `version_no` int DEFAULT 1 COMMENT '版本号',
  `account_set_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '帐套ID',
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_salary_rule_type_code_set` (`rule_type`,`rule_code`,`account_set_id`),
  KEY `idx_salary_rule_type_set` (`rule_type`,`account_set_id`),
  KEY `idx_salary_rule_enabled` (`is_enabled`),
  KEY `idx_salary_rule_period` (`effective_start_period`,`effective_end_period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='薪酬规则定义表';
