import type { PayrollOption, SalaryItemTemplate } from '#/views/finance/cashier/settings/payroll/types';

export const directionOptions: PayrollOption[] = [
  { label: '收入项', value: 'income' },
  { label: '扣减项', value: 'deduct' },
  { label: '结果项', value: 'result' },
  { label: '中间项', value: 'middle' },
  { label: '公司承担项', value: 'company' },
];

export const categoryOptions: PayrollOption[] = [
  { label: '固定工资', value: 'BASIC' },
  { label: '浮动工资', value: 'FLOATING' },
  { label: '补贴项目', value: 'ALLOWANCE' },
  { label: '考勤调整', value: 'ATTENDANCE' },
  { label: '五险一金', value: 'INSURANCE' },
  { label: '税务项目', value: 'TAX' },
  { label: '汇总项目', value: 'RESULT' },
  { label: '自定义项目', value: 'CUSTOM' },
];

export const inputModeOptions: PayrollOption[] = [
  { label: '手工录入', value: 'MANUAL' },
  { label: '公式计算', value: 'FORMULA' },
  { label: '导入带入', value: 'IMPORT' },
  { label: '同步带入', value: 'SYNC' },
  { label: '固定值', value: 'FIXED' },
];

export const dataTypeOptions: PayrollOption[] = [
  { label: '金额/小数', value: 'DECIMAL' },
  { label: '整数', value: 'INTEGER' },
  { label: '文本', value: 'TEXT' },
  { label: '日期', value: 'DATE' },
  { label: '布尔', value: 'BOOLEAN' },
];

export const unitOptions: PayrollOption[] = [
  { label: '元', value: 'CNY' },
  { label: '百分比', value: 'PERCENT' },
  { label: '小时', value: 'HOUR' },
  { label: '天', value: 'DAY' },
  { label: '次', value: 'TIMES' },
  { label: '文本', value: 'TEXT' },
];

export const defaultSourceOptions: PayrollOption[] = [{ label: '手工输入', value: 'INPUT' }];

export const displayOptions: PayrollOption[] = [
  { label: '全部显示', value: 'ALL' },
  { label: '不显示', value: 'NONE' },
  { label: 'L1、L2 级显示', value: 'LEVEL:L1,L2' },
  { label: 'M1 及以上显示', value: 'LEVEL:M1+' },
  { label: 'E1 级显示', value: 'LEVEL:E1' },
];

export const permissionOptions: PayrollOption[] = [
  { label: '系统', value: 'SYS' },
  { label: '人事', value: 'HR' },
  { label: '财务', value: 'FIN' },
  { label: '人事/财务', value: 'HR|FIN' },
  { label: '只读', value: 'READONLY' },
];

export const visibleScopeOptions: PayrollOption[] = [
  { label: '全部可见', value: 'ALL' },
  { label: '人事可见', value: 'HR' },
  { label: '财务可见', value: 'FIN' },
  { label: '人事/财务可见', value: 'HR|FIN' },
  { label: '仅管理员', value: 'ADMIN' },
  { label: '不可见', value: 'NONE' },
];

export const editableScopeOptions: PayrollOption[] = permissionOptions;

export const payrollImportSolutionName = '工资项目元数据导入方案';
export const payrollImportConfigSheetName = '工资项目元数据';
export const payrollImportConfigTable = 'LMBill@Bil_Salary_Item_Meta';

export const payrollImportFieldTemplates = [
  { name: 'item_code', title: '项目编码' },
  { name: 'item_name', title: '项目名称' },
  { name: 'display_name', title: '显示名称' },
  { name: 'item_category', title: '项目分类' },
  { name: 'item_subcategory', title: '项目子分类' },
  { name: 'item_direction', title: '项目方向' },
  { name: 'input_mode', title: '录入模式' },
  { name: 'data_type', title: '数据类型' },
  { name: 'unit', title: '单位' },
  { name: 'default_value', title: '默认值' },
  { name: 'default_source', title: '默认值来源' },
  { name: 'display_group', title: '显示分组' },
  { name: 'salary_slip_display', title: '工资条显示' },
  { name: 'setting_permission', title: '设置权限' },
  { name: 'visible_scope', title: '可见范围' },
  { name: 'editable_scope', title: '可编辑范围' },
  { name: 'is_enabled', title: '启用状态' },
  { name: 'is_tax_item', title: '是否计税项' },
  { name: 'is_formula_item', title: '是否公式项' },
  { name: 'is_bonus_item', title: '是否奖金项' },
  { name: 'is_custom_item', title: '是否自定义项' },
  { name: 'required_flag', title: '是否必填' },
  { name: 'negative_allowed', title: '是否允许负数' },
  { name: 'value_precision', title: '数值精度' },
  { name: 'sort_no', title: '排序号' },
  { name: 'version_no', title: '版本号' },
  { name: 'validation_rule', title: '校验规则' },
  { name: 'source_table', title: '来源表' },
  { name: 'source_field', title: '来源字段' },
  { name: 'source_expr', title: '来源表达式' },
  { name: 'tax_rule_code', title: '税规则编码' },
  { name: 'social_insurance_rule_code', title: '社保规则编码' },
  { name: 'housing_fund_rule_code', title: '公积金规则编码' },
  { name: 'effective_start_date', title: '生效开始日期' },
  { name: 'effective_end_date', title: '生效结束日期' },
  { name: 'description', title: '说明' },
  { name: 'remark', title: '备注' },
];

export const commonItemTemplates: SalaryItemTemplate[] = [
  {
    title: '基本工资',
    item_code: 'basic_salary',
    item_name: '基本工资',
    item_category: 'BASIC',
    item_direction: 'income',
    input_mode: 'MANUAL',
    display_group: '固定工资',
    description: '员工固定工资基础项',
    sort_no: 10,
  },
  {
    title: '岗位工资',
    item_code: 'post_salary',
    item_name: '岗位工资',
    item_category: 'BASIC',
    item_direction: 'income',
    input_mode: 'MANUAL',
    display_group: '固定工资',
    description: '按岗位设置的固定工资项',
    sort_no: 20,
  },
  {
    title: '绩效工资',
    item_code: 'performance_salary',
    item_name: '绩效工资',
    item_category: 'FLOATING',
    item_direction: 'income',
    input_mode: 'MANUAL',
    display_group: '浮动工资',
    description: '按绩效考核浮动的工资项',
    sort_no: 30,
  },
  {
    title: '奖金',
    item_code: 'bonus',
    item_name: '奖金',
    item_category: 'FLOATING',
    item_direction: 'income',
    input_mode: 'MANUAL',
    display_group: '浮动工资',
    description: '奖金或奖励类工资项',
    is_bonus_item: 1,
    sort_no: 40,
  },
  {
    title: '补贴',
    item_code: 'allowance',
    item_name: '补贴',
    item_category: 'ALLOWANCE',
    item_direction: 'income',
    input_mode: 'MANUAL',
    display_group: '补贴项目',
    description: '餐补、话补、交通补贴等',
    sort_no: 50,
  },
  {
    title: '加班费',
    item_code: 'overtime_pay',
    item_name: '加班费',
    item_category: 'ATTENDANCE',
    item_direction: 'income',
    input_mode: 'MANUAL',
    display_group: '考勤调整',
    description: '根据加班工时计算的工资项',
    sort_no: 60,
  },
  { title: '个人养老保险', item_code: 'personal_pension_insurance', item_name: '个人养老保险', item_category: 'INSURANCE', item_direction: 'deduct', input_mode: 'FORMULA', display_group: '五险一金', description: '员工个人承担养老保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 64 },
  { title: '个人医疗保险', item_code: 'personal_medical_insurance', item_name: '个人医疗保险', item_category: 'INSURANCE', item_direction: 'deduct', input_mode: 'FORMULA', display_group: '五险一金', description: '员工个人承担医疗保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 65 },
  { title: '个人失业保险', item_code: 'personal_unemployment_insurance', item_name: '个人失业保险', item_category: 'INSURANCE', item_direction: 'deduct', input_mode: 'FORMULA', display_group: '五险一金', description: '员工个人承担失业保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 66 },
  { title: '个人工伤保险', item_code: 'personal_work_injury_insurance', item_name: '个人工伤保险', item_category: 'INSURANCE', item_direction: 'deduct', input_mode: 'FORMULA', display_group: '五险一金', description: '员工个人承担工伤保险，一般为 0，可按规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 67 },
  { title: '个人生育保险', item_code: 'personal_maternity_insurance', item_name: '个人生育保险', item_category: 'INSURANCE', item_direction: 'deduct', input_mode: 'FORMULA', display_group: '五险一金', description: '员工个人承担生育保险，一般为 0，可按规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 68 },
  {
    title: '个人社保',
    item_code: 'personal_social_insurance',
    item_name: '个人社保',
    item_category: 'INSURANCE',
    item_direction: 'deduct',
    input_mode: 'FORMULA',
    display_group: '五险一金',
    description: '员工个人承担社保，按社保规则自动计算',
    social_insurance_rule_code: 'SOCIAL_INSURANCE_SIMPLE_CN_DEFAULT',
    sort_no: 70,
  },
  {
    title: '个人公积金',
    item_code: 'personal_housing_fund',
    item_name: '个人公积金',
    item_category: 'INSURANCE',
    item_direction: 'deduct',
    input_mode: 'FORMULA',
    display_group: '五险一金',
    description: '员工个人承担公积金，按公积金规则自动计算',
    housing_fund_rule_code: 'HOUSING_FUND_SIMPLE_CN_DEFAULT',
    sort_no: 80,
  },
  { title: '公司养老保险', item_code: 'company_pension_insurance', item_name: '公司养老保险', item_category: 'INSURANCE', item_direction: 'company', input_mode: 'FORMULA', display_group: '五险一金', description: '公司承担养老保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 71 },
  { title: '公司医疗保险', item_code: 'company_medical_insurance', item_name: '公司医疗保险', item_category: 'INSURANCE', item_direction: 'company', input_mode: 'FORMULA', display_group: '五险一金', description: '公司承担医疗保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 72 },
  { title: '公司失业保险', item_code: 'company_unemployment_insurance', item_name: '公司失业保险', item_category: 'INSURANCE', item_direction: 'company', input_mode: 'FORMULA', display_group: '五险一金', description: '公司承担失业保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 73 },
  { title: '公司工伤保险', item_code: 'company_work_injury_insurance', item_name: '公司工伤保险', item_category: 'INSURANCE', item_direction: 'company', input_mode: 'FORMULA', display_group: '五险一金', description: '公司承担工伤保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 74 },
  { title: '公司生育保险', item_code: 'company_maternity_insurance', item_name: '公司生育保险', item_category: 'INSURANCE', item_direction: 'company', input_mode: 'FORMULA', display_group: '五险一金', description: '公司承担生育保险，按职级/员工命中的社保规则计算', social_insurance_rule_code: 'SOCIAL_INSURANCE_CN_COMPONENT_DEFAULT', sort_no: 75 },
  {
    title: '公司社保',
    item_code: 'company_social_insurance',
    item_name: '公司社保',
    item_category: 'INSURANCE',
    item_direction: 'company',
    input_mode: 'FORMULA',
    display_group: '五险一金',
    description: '公司承担社保，按社保规则自动计算',
    social_insurance_rule_code: 'SOCIAL_INSURANCE_SIMPLE_CN_DEFAULT',
    sort_no: 81,
  },
  {
    title: '公司公积金',
    item_code: 'company_housing_fund',
    item_name: '公司公积金',
    item_category: 'INSURANCE',
    item_direction: 'company',
    input_mode: 'FORMULA',
    display_group: '五险一金',
    description: '公司承担公积金，按公积金规则自动计算',
    housing_fund_rule_code: 'HOUSING_FUND_SIMPLE_CN_DEFAULT',
    sort_no: 82,
  },
  {
    title: '公司承担合计',
    item_code: 'company_contribution_total',
    item_name: '公司承担合计',
    item_category: 'INSURANCE',
    item_direction: 'company',
    input_mode: 'FORMULA',
    display_group: '五险一金',
    description: '公司社保与公司公积金等公司承担项目汇总',
    is_formula_item: 1,
    sort_no: 83,
  },
  { title: '个人五险一金合计', item_code: 'personal_contribution_total', item_name: '个人五险一金合计', item_category: 'RESULT', item_direction: 'middle', input_mode: 'FORMULA', display_group: '五险一金', description: '个人社保合计 + 个人公积金', is_formula_item: 1, sort_no: 84 },
  {
    title: '税前扣除合计',
    item_code: 'pretax_deduction_total',
    item_name: '税前扣除合计',
    item_category: 'RESULT',
    item_direction: 'middle',
    input_mode: 'FORMULA',
    display_group: '税务项目',
    description: '社保、公积金等税前扣除汇总项',
    is_formula_item: 1,
    sort_no: 85,
  },
  {
    title: '应税收入',
    item_code: 'tax_base',
    item_name: '应税收入',
    item_category: 'RESULT',
    item_direction: 'middle',
    input_mode: 'FORMULA',
    display_group: '税务项目',
    description: '用于税规则计算的基础金额',
    is_formula_item: 1,
    sort_no: 88,
  },
  {
    title: '个人所得税',
    item_code: 'personal_income_tax',
    item_name: '个人所得税',
    item_category: 'TAX',
    item_direction: 'deduct',
    input_mode: 'FORMULA',
    display_group: '税务项目',
    description: '工资个税项目，按税规则自动计算',
    is_tax_item: 1,
    sort_no: 90,
    tax_rule_code: 'SALARY_TAX_SIMPLE_CN_MONTHLY',
  },
  {
    title: '其他扣款',
    item_code: 'other_deduction',
    item_name: '其他扣款',
    item_category: 'CUSTOM',
    item_direction: 'deduct',
    input_mode: 'MANUAL',
    display_group: '自定义项目',
    description: '除社保、公积金、个税外的其他扣减项',
    sort_no: 100,
  },
  {
    title: '应发合计',
    item_code: 'should_pay_total',
    item_name: '应发合计',
    item_category: 'RESULT',
    item_direction: 'result',
    input_mode: 'FORMULA',
    display_group: '汇总项目',
    description: '收入项自动汇总结果',
    is_formula_item: 1,
    sort_no: 110,
  },
  {
    title: '扣减合计',
    item_code: 'deduct_total',
    item_name: '扣减合计',
    item_category: 'RESULT',
    item_direction: 'result',
    input_mode: 'FORMULA',
    display_group: '汇总项目',
    description: '扣减项自动汇总结果',
    is_formula_item: 1,
    sort_no: 120,
  },
  {
    title: '实发工资',
    item_code: 'real_pay',
    item_name: '实发工资',
    item_category: 'RESULT',
    item_direction: 'result',
    input_mode: 'FORMULA',
    display_group: '汇总项目',
    description: '应发减扣减后的最终实发结果',
    is_formula_item: 1,
    sort_no: 130,
  },
];
