-- 01_create_hr_tables.sql
-- siweiOA HR 第一批目标表创建脚本
-- 非破坏性：只 CREATE TABLE IF NOT EXISTS，不删除、不清空。

USE `LMBill`;

CREATE TABLE IF NOT EXISTS `Bil_HR_Employee_Profile` (
  `rowid` varchar(64) NOT NULL COMMENT '主键',
  `employee_no` varchar(64) DEFAULT NULL COMMENT '员工编号',
  `employee_name` varchar(100) DEFAULT NULL COMMENT '员工姓名',
  `gender` varchar(20) DEFAULT NULL COMMENT '性别',
  `birth_date` date DEFAULT NULL COMMENT '出生日期',
  `id_card` varchar(64) DEFAULT NULL COMMENT '身份证号',
  `phone` varchar(64) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `depart_id` varchar(64) DEFAULT NULL COMMENT '部门ID',
  `depart_name` varchar(128) DEFAULT NULL COMMENT '部门名称',
  `position_name` varchar(128) DEFAULT NULL COMMENT '岗位名称',
  `job_level` varchar(64) DEFAULT NULL COMMENT '职级',
  `manager_id` varchar(64) DEFAULT NULL COMMENT '上级ID',
  `hire_date` date DEFAULT NULL COMMENT '入职日期',
  `probation_end_date` date DEFAULT NULL COMMENT '试用期结束日期',
  `status` varchar(64) DEFAULT NULL COMMENT '状态',
  `address` varchar(500) DEFAULT NULL COMMENT '地址',
  `emergency_contact` varchar(100) DEFAULT NULL COMMENT '紧急联系人',
  `emergency_phone` varchar(64) DEFAULT NULL COMMENT '紧急联系电话',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '开户行',
  `bank_account` varchar(128) DEFAULT NULL COMMENT '银行账号',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `source_system` varchar(64) DEFAULT NULL COMMENT '来源系统',
  `source_table` varchar(128) DEFAULT NULL COMMENT '来源表',
  `source_id` varchar(128) DEFAULT NULL COMMENT '来源ID',
  `migration_batch_no` varchar(64) DEFAULT NULL COMMENT '迁移批次',
  `createuser` varchar(100) DEFAULT NULL,
  `createtime` datetime DEFAULT NULL,
  `updateuser` varchar(100) DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `wfid` varchar(64) DEFAULT NULL,
  `flowstate` int DEFAULT NULL,
  `ReportID` varchar(64) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `lingma_sys_is_delete` int DEFAULT 0,
  PRIMARY KEY (`rowid`),
  KEY `idx_hr_emp_source` (`source_system`, `source_table`, `source_id`),
  KEY `idx_hr_emp_no` (`employee_no`),
  KEY `idx_hr_emp_depart` (`depart_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='HR员工档案';

CREATE TABLE IF NOT EXISTS `Bil_HR_Project_Resource_Hours` (
  `rowid` varchar(64) NOT NULL COMMENT '主键',
  `hours_code` varchar(64) DEFAULT NULL COMMENT '工时编号',
  `project_id` varchar(64) DEFAULT NULL COMMENT '项目ID',
  `employee_id` varchar(64) DEFAULT NULL COMMENT '员工ID',
  `employee_name` varchar(100) DEFAULT NULL COMMENT '员工姓名',
  `work_date` date DEFAULT NULL COMMENT '工作日期',
  `hours` decimal(18,2) DEFAULT NULL COMMENT '工时',
  `status` varchar(64) DEFAULT NULL COMMENT '状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `source_system` varchar(64) DEFAULT NULL,
  `source_table` varchar(128) DEFAULT NULL,
  `source_id` varchar(128) DEFAULT NULL,
  `migration_batch_no` varchar(64) DEFAULT NULL,
  `createuser` varchar(100) DEFAULT NULL,
  `createtime` datetime DEFAULT NULL,
  `updateuser` varchar(100) DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `wfid` varchar(64) DEFAULT NULL,
  `flowstate` int DEFAULT NULL,
  `ReportID` varchar(64) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `lingma_sys_is_delete` int DEFAULT 0,
  PRIMARY KEY (`rowid`),
  KEY `idx_hr_hours_project` (`project_id`),
  KEY `idx_hr_hours_employee` (`employee_id`),
  KEY `idx_hr_hours_date` (`work_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='HR项目工时';

CREATE TABLE IF NOT EXISTS `Bil_HR_Migration_Log` (
  `rowid` varchar(64) NOT NULL COMMENT '主键',
  `batch_no` varchar(64) DEFAULT NULL COMMENT '迁移批次',
  `source_database` varchar(64) DEFAULT NULL COMMENT '来源库',
  `source_table` varchar(128) DEFAULT NULL COMMENT '来源表',
  `target_table` varchar(128) DEFAULT NULL COMMENT '目标表',
  `source_count` int DEFAULT 0 COMMENT '来源数量',
  `target_count` int DEFAULT 0 COMMENT '目标数量',
  `success_count` int DEFAULT 0 COMMENT '成功数量',
  `failed_count` int DEFAULT 0 COMMENT '失败数量',
  `status` varchar(64) DEFAULT NULL COMMENT '状态',
  `error_message` text DEFAULT NULL COMMENT '错误信息',
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `createuser` varchar(100) DEFAULT NULL,
  `createtime` datetime DEFAULT NULL,
  PRIMARY KEY (`rowid`),
  KEY `idx_hr_migration_batch` (`batch_no`),
  KEY `idx_hr_migration_table` (`source_table`, `target_table`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='HR迁移日志';
