-- 存货核算模块无约束建表 SQL
-- 说明：无主键、无唯一索引、无外键、无 NOT NULL。
-- 范围：成本计算表、成本调整单、成本调整单明细、入库成本调整单、入库成本调整单明细。

CREATE TABLE IF NOT EXISTS `erp_inventory_cost_calc` (
  `id` varchar(64) DEFAULT NULL COMMENT '记录ID',
  `period_code` varchar(7) DEFAULT NULL COMMENT '期间编码，格式YYYY-MM',
  `fiscal_year` int DEFAULT NULL COMMENT '会计年度',
  `period_month` int DEFAULT NULL COMMENT '会计期间月份',
  `biz_date` date DEFAULT NULL COMMENT '业务日期',
  `biz_time` datetime DEFAULT NULL COMMENT '业务时间',
  `biz_type` varchar(50) DEFAULT NULL COMMENT '业务类型',
  `biz_no` varchar(100) DEFAULT NULL COMMENT '业务单号',
  `biz_id` varchar(64) DEFAULT NULL COMMENT '业务主表ID',
  `biz_item_id` varchar(64) DEFAULT NULL COMMENT '业务明细ID',
  `product_id` varchar(64) DEFAULT NULL COMMENT '商品ID',
  `product_code` varchar(100) DEFAULT NULL COMMENT '商品编码',
  `product_name` varchar(200) DEFAULT NULL COMMENT '商品名称',
  `product_category_id` varchar(64) DEFAULT NULL COMMENT '商品分类ID',
  `product_category_name` varchar(200) DEFAULT NULL COMMENT '商品分类名称',
  `product_model` varchar(200) DEFAULT NULL COMMENT '规格型号',
  `unit_id` varchar(64) DEFAULT NULL COMMENT '单位ID',
  `unit_name` varchar(100) DEFAULT NULL COMMENT '单位名称',
  `warehouse_id` varchar(64) DEFAULT NULL COMMENT '仓库ID',
  `warehouse_name` varchar(200) DEFAULT NULL COMMENT '仓库名称',
  `opening_count` decimal(24,6) DEFAULT NULL COMMENT '期初数量',
  `opening_amount` decimal(24,6) DEFAULT NULL COMMENT '期初金额',
  `opening_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '期初单位成本',
  `in_count` decimal(24,6) DEFAULT NULL COMMENT '入库数量',
  `in_amount` decimal(24,6) DEFAULT NULL COMMENT '入库金额',
  `in_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '入库单位成本',
  `out_count` decimal(24,6) DEFAULT NULL COMMENT '出库数量',
  `out_amount` decimal(24,6) DEFAULT NULL COMMENT '出库成本金额',
  `out_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '出库单位成本',
  `ending_count` decimal(24,6) DEFAULT NULL COMMENT '结存数量',
  `ending_amount` decimal(24,6) DEFAULT NULL COMMENT '结存金额',
  `ending_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '结存单位成本',
  `cost_method` varchar(50) DEFAULT NULL COMMENT '计价方法',
  `source_type` varchar(50) DEFAULT NULL COMMENT '成本来源类型',
  `source_no` varchar(100) DEFAULT NULL COMMENT '成本来源单号',
  `exception_flag` varchar(100) DEFAULT NULL COMMENT '异常标记',
  `exception_message` varchar(500) DEFAULT NULL COMMENT '异常说明',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `company_name` varchar(255) DEFAULT NULL COMMENT '公司名称',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例ID',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表ID',
  `description` text COMMENT '摘要',
  `lingma_sys_is_delete` int DEFAULT NULL COMMENT '是否删除',
  `lingma_sys_ent` varchar(50) DEFAULT 'NewApp' COMMENT '企业标识'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='存货核算成本计算表';

CREATE TABLE IF NOT EXISTS `erp_inventory_cost_adjust` (
  `id` varchar(64) DEFAULT NULL COMMENT '调整单ID',
  `no` varchar(100) DEFAULT NULL COMMENT '调整单号',
  `adjust_date` date DEFAULT NULL COMMENT '调整日期',
  `period_code` varchar(7) DEFAULT NULL COMMENT '期间编码，格式YYYY-MM',
  `adjust_type` varchar(50) DEFAULT NULL COMMENT '调整类型',
  `reason` varchar(500) DEFAULT NULL COMMENT '调整原因',
  `total_adjust_amount` decimal(24,6) DEFAULT NULL COMMENT '调整金额合计',
  `status` int DEFAULT NULL COMMENT '状态：10草稿 20已审批',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `company_name` varchar(255) DEFAULT NULL COMMENT '公司名称',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例ID',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表ID',
  `description` text COMMENT '摘要',
  `lingma_sys_is_delete` int DEFAULT NULL COMMENT '是否删除',
  `lingma_sys_ent` varchar(50) DEFAULT 'NewApp' COMMENT '企业标识'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='存货核算成本调整单';

CREATE TABLE IF NOT EXISTS `erp_inventory_cost_adjust_item` (
  `id` varchar(64) DEFAULT NULL COMMENT '调整明细ID',
  `adjust_id` varchar(64) DEFAULT NULL COMMENT '调整单ID',
  `adjust_no` varchar(100) DEFAULT NULL COMMENT '调整单号',
  `product_id` varchar(64) DEFAULT NULL COMMENT '商品ID',
  `product_code` varchar(100) DEFAULT NULL COMMENT '商品编码',
  `product_name` varchar(200) DEFAULT NULL COMMENT '商品名称',
  `product_model` varchar(200) DEFAULT NULL COMMENT '规格型号',
  `unit_id` varchar(64) DEFAULT NULL COMMENT '单位ID',
  `unit_name` varchar(100) DEFAULT NULL COMMENT '单位名称',
  `warehouse_id` varchar(64) DEFAULT NULL COMMENT '仓库ID',
  `warehouse_name` varchar(200) DEFAULT NULL COMMENT '仓库名称',
  `before_count` decimal(24,6) DEFAULT NULL COMMENT '调整前结存数量',
  `before_amount` decimal(24,6) DEFAULT NULL COMMENT '调整前结存金额',
  `before_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '调整前单位成本',
  `adjust_amount` decimal(24,6) DEFAULT NULL COMMENT '调整金额',
  `after_count` decimal(24,6) DEFAULT NULL COMMENT '调整后结存数量',
  `after_amount` decimal(24,6) DEFAULT NULL COMMENT '调整后结存金额',
  `after_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '调整后单位成本',
  `reason` varchar(500) DEFAULT NULL COMMENT '调整原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `lingma_sys_is_delete` int DEFAULT NULL COMMENT '是否删除',
  `lingma_sys_ent` varchar(50) DEFAULT 'NewApp' COMMENT '企业标识'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='存货核算成本调整单明细';

CREATE TABLE IF NOT EXISTS `erp_inventory_inbound_cost_adjust` (
  `id` varchar(64) DEFAULT NULL COMMENT '入库成本调整单ID',
  `no` varchar(100) DEFAULT NULL COMMENT '入库成本调整单号',
  `adjust_date` date DEFAULT NULL COMMENT '调整日期',
  `period_code` varchar(7) DEFAULT NULL COMMENT '期间编码，格式YYYY-MM',
  `source_type` varchar(50) DEFAULT NULL COMMENT '来源类型',
  `source_id` varchar(64) DEFAULT NULL COMMENT '来源单据ID',
  `source_no` varchar(100) DEFAULT NULL COMMENT '来源单据号',
  `allocation_method` varchar(50) DEFAULT NULL COMMENT '分摊方式',
  `total_original_amount` decimal(24,6) DEFAULT NULL COMMENT '原入库金额合计',
  `total_adjust_amount` decimal(24,6) DEFAULT NULL COMMENT '调整金额合计',
  `total_adjusted_amount` decimal(24,6) DEFAULT NULL COMMENT '调整后金额合计',
  `status` int DEFAULT NULL COMMENT '状态：10草稿 20已审批',
  `reason` varchar(500) DEFAULT NULL COMMENT '调整原因',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `company_name` varchar(255) DEFAULT NULL COMMENT '公司名称',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `wfid` varchar(32) DEFAULT NULL COMMENT '流程实例ID',
  `flowstate` int DEFAULT NULL COMMENT '流程状态',
  `ReportID` varchar(32) DEFAULT NULL COMMENT '报表ID',
  `description` text COMMENT '摘要',
  `lingma_sys_is_delete` int DEFAULT NULL COMMENT '是否删除',
  `lingma_sys_ent` varchar(50) DEFAULT 'NewApp' COMMENT '企业标识'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='入库成本调整单';

CREATE TABLE IF NOT EXISTS `erp_inventory_inbound_cost_adjust_item` (
  `id` varchar(64) DEFAULT NULL COMMENT '入库成本调整明细ID',
  `adjust_id` varchar(64) DEFAULT NULL COMMENT '入库成本调整单ID',
  `adjust_no` varchar(100) DEFAULT NULL COMMENT '入库成本调整单号',
  `source_type` varchar(50) DEFAULT NULL COMMENT '来源类型',
  `source_id` varchar(64) DEFAULT NULL COMMENT '来源单据ID',
  `source_no` varchar(100) DEFAULT NULL COMMENT '来源单据号',
  `source_item_id` varchar(64) DEFAULT NULL COMMENT '来源单据明细ID',
  `product_id` varchar(64) DEFAULT NULL COMMENT '商品ID',
  `product_code` varchar(100) DEFAULT NULL COMMENT '商品编码',
  `product_name` varchar(200) DEFAULT NULL COMMENT '商品名称',
  `product_model` varchar(200) DEFAULT NULL COMMENT '规格型号',
  `unit_id` varchar(64) DEFAULT NULL COMMENT '单位ID',
  `unit_name` varchar(100) DEFAULT NULL COMMENT '单位名称',
  `warehouse_id` varchar(64) DEFAULT NULL COMMENT '仓库ID',
  `warehouse_name` varchar(200) DEFAULT NULL COMMENT '仓库名称',
  `original_count` decimal(24,6) DEFAULT NULL COMMENT '原入库数量',
  `original_amount` decimal(24,6) DEFAULT NULL COMMENT '原入库金额',
  `original_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '原入库单位成本',
  `adjust_amount` decimal(24,6) DEFAULT NULL COMMENT '调整金额',
  `adjusted_amount` decimal(24,6) DEFAULT NULL COMMENT '调整后入库金额',
  `adjusted_unit_cost` decimal(24,6) DEFAULT NULL COMMENT '调整后入库单位成本',
  `allocation_method` varchar(50) DEFAULT NULL COMMENT '分摊方式',
  `reason` varchar(500) DEFAULT NULL COMMENT '调整原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `account_set_id` varchar(64) DEFAULT NULL COMMENT '账套ID',
  `createuser` varchar(100) DEFAULT NULL COMMENT '创建人',
  `createtime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateuser` varchar(100) DEFAULT NULL COMMENT '修改人',
  `updatetime` datetime DEFAULT NULL COMMENT '修改时间',
  `lingma_sys_is_delete` int DEFAULT NULL COMMENT '是否删除',
  `lingma_sys_ent` varchar(50) DEFAULT 'NewApp' COMMENT '企业标识'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='入库成本调整单明细';
